#!/bin/bash

haircut_flag=$1
person=$2
# removes '--' from flag
match=--
replace_with=''
haircut_type=${haircut_flag/$match/$replace_with}
haircut_query="$haircut_type+haircut"
 # echo ht:$haircut_type
 # echo hq:$haircut_query
 # echo person:.$person.

# Open Slideshow
# open http://theslideshow.net/#simple/$haircut_type
open http://theslideshow.net/#advanced/search-advanced-query=$haircut_query&site=&safesearch=Strict&imageSize=Large&colorization=--&colorFilter=--&fileType=--&imageType=--&rights=--

message="$person might just have that haircut tomorrow."

if [ $person == "Erica" ]; then
  message="$person wouldn't be caught dead with a haircut like that."
fi

if [ $person == "Adrian" ]; then
  message="$person wishes they wwe that lucky."
fi

echo $message
echo
